project_id = "dwbglccmxalypjwjczmp"

[functions.chat-guidance]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.research-agent]
verify_jwt = false